### ISSUE TITLE
ERROR:pytest_commander.api:Exception on /api/v1/result-tree [GET]

### ISSUE THREAD

**Issue by schmacko234** [ryanc414/pytest_runner#14]
Hi,

i get the following error when starting pytest_commander. I work on a conda env.

`ERROR:pytest_commander.api:Exception on /api/v1/result-tree [GET]
Traceback (most recent call last):
  File "c:\users\lto\miniconda3\envs\selide\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lto\miniconda3\envs\selide\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lto\miniconda3\envs\selide\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lto\miniconda3\envs\selide\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lto\miniconda3\envs\selide\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lto\miniconda3\envs\selide\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lto\miniconda3\envs\selide\lib\site-packages\pytest_commander\api.py", line 45, in tree
    return branch_schema.dump(test_runner.result_tree)
  File "c:\users\lto\miniconda3\envs\selide\lib\site-packages\marshmallow\schema.py", line 547, in dump
    result = self._serialize(processed_obj, many=many)
  File "c:\users\lto\miniconda3\envs\selide\lib\site-packages\marshmallow\schema.py", line 515, in _serialize
    value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
  File "c:\users\lto\miniconda3\envs\selide\lib\site-packages\marshmallow\fields.py", line 310, in serialize
    value = self.get_value(obj, attr, accessor=accessor)
  File "c:\users\lto\miniconda3\envs\selide\lib\site-packages\marshmallow\fields.py", line 239, in get_value
    return accessor_func(obj, check_key, default)
  File "c:\users\lto\miniconda3\envs\selide\lib\site-packages\marshmallow\schema.py", line 472, in get_attribute
    return get_value(obj, attr, default)
  File "c:\users\lto\miniconda3\envs\selide\lib\site-packages\marshmallow\utils.py", line 239, in get_value
    return _get_value_for_key(obj, key, default)
  File "c:\users\lto\miniconda3\envs\selide\lib\site-packages\marshmallow\utils.py", line 253, in _get_value_for_key
    return getattr(obj, key, default)
  File "c:\users\lto\miniconda3\envs\selide\lib\site-packages\pytest_commander\result_tree.py", line 187, in short_id
    return self.nodeid.short_id
  File "c:\users\lto\miniconda3\envs\selide\lib\site-packages\pytest_commander\nodeid.py", line 125, in short_id
    return self.fragments[-1].val
IndexError: list index out of range
`

**Comment by ryanc414** [comment]
Hi, thanks for raising this issue. Could you please share some more details about the tests you are running and what args you are passing to pytest_commander on the command line?

**Comment by schmacko234** [comment]
I have tried pycharm, cmd and anaconda prompt with following args in my working directory:
pytest_commander ./

I have a python file in this directory with tests as functions inside.

**Comment by ryanc414** [comment]
Can you please try updating to the latest 2.6.0 release and let me know if you still have the issue?

If so, are you by any chance running from the root directory `/`?

**Comment by schmacko234** [comment]
Hi, after some refactoring work on my script, pytest_commander now starts without an error.
But i cant see any name of my test in the browser ui. when i press the play button though, the test starts normally.
Please refer to the screenshot. 

https://pasteboard.co/K6Aa4N8.jpg

**Comment by ryanc414** [comment]
> Hi, after some refactoring work on my script, pytest_commander now starts without an error.
> But i cant see any name of my test in the browser ui. when i press the play button though, the test starts normally.
> Please refer to the screenshot.
> 
> https://pasteboard.co/K6Aa4N8.jpg

That issue should be resolved in the latest release, please can you run `pip install -U pytest-commander` and try again?

**Comment by schmacko234** [comment]
Does work now, thank you very much! Can be closed.
