### ISSUE TITLE
ModuleNotFoundError: No module named 'SocketServer'

### ISSUE THREAD

**Issue by nullwiz** [ryanc414/pytest_runner#3]
Hello ryan,

Let me first of all say I love this! I am planning on extending this and be able to integrate it with selenium-grid.. being able to see in real time how the test is being executed :). 

I know this is not an easy task. To start up, I was able to add additional configuration arguments for pytest-testconfig (--tc-file) to point to different environments.

However, I am having the following bug: 

- When using pycharm, and running a test, I get 

```

============================ no tests ran in 0.01s ============================
CRITICAL:__main__:View in your browser at http://localhost:5000/
Traceback (most recent call last):
  File "C:\Users\nullwiz\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 58, in <module>
    from http.server import BaseHTTPRequestHandler
  File "C:\Users\nullwiz\AppData\Local\Programs\Python\Python37\lib\http\server.py", line 92, in <module>
    import email.utils
ModuleNotFoundError: No module named 'email.utils'; 'email' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\nullwiz\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\nullwiz\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\nullwiz\AppData\Local\Programs\Python\Python37\lib\site-packages\pytest_web_ui-1.3.1-py3.7.egg\pytest_web_ui\runner.py", line 14, in <module>
  File "C:\Users\nullwiz\AppData\Local\Programs\Python\Python37\lib\site-packages\flask_socketio\__init__.py", line 18, in <module>
    import flask
  File "C:\Users\nullwiz\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\__init__.py", line 16, in <module>
    from werkzeug.exceptions import abort
  File "C:\Users\nullwiz\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\__init__.py", line 15, in <module>
    from .serving import run_simple
  File "C:\Users\nullwiz\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\serving.py", line 61, in <module>
    import SocketServer as socketserver
ModuleNotFoundError: No module named 'SocketServer

```

Not sure why this happens. 
If I run debugging, I can see the test starts. However, I get ERROR: File Not Found for the specific test that has already been collected without an issue.

I plan to keep on working on this, as I will like to extend its capabilities -- while also adding a Graphana dashboard with react for Allure API.

If I have any update I will post it here.

**Comment by nullwiz** [comment]
Okay, managed to fix the error. It was related to where I ran the module. When running with debugger, it failed. 
Running it like this :

`python -m pytest_web_ui --tc_file={config_file} {test_dir}`

worked just fine!
